name: timetracker
description: Papierkram.de - TimeTracker as flutter app

version: 1.5.4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  flutter_secure_storage: ^3.3.3
  json_annotation: ^3.0.1
  duration: ^2.0.14
  uuid: ^2.1.0
  flutter_typeahead: ^1.8.3
  flutter_easyrefresh: ^2.1.1
  html_unescape: ^1.0.1+3
  flutter_cupertino_settings: ^0.3.1
  url_launcher: ^5.4.10
  in_app_purchase: ^0.3.4
  app_review: ^1.1.2
  file_picker: ^1.11.0+3
  open_file: ^3.0.1
  flutter_cache_manager: ^1.4.1
  device_info: '>=0.4.2+4 <2.0.0'
  package_info: '>=0.4.1 <2.0.0'
  sentry: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/icon_android.png"
  image_path_ios: "assets/images/icon_ios.png"
  adaptive_icon_background: "#B9D5DE"
  adaptive_icon_foreground: "assets/images/icon_android.png"

flutter_native_splash:
  image: "assets/images/icon_splash.png"
  color: "#B9D5DE"
