name: time_tracker
description: Papierkram.de - TimeTracker as flutter app

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  flutter_secure_storage: ^3.2.1+1
  json_annotation: ^2.0.0
  duration: ^2.0.4
  uuid: ^2.0.0
  flutter_typeahead: ^1.6.0
  flutter_easyrefresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
