name: timetracker
description: Papierkram.de - TimeTracker as flutter app

version: 1.3.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+5
  flutter_secure_storage: ^3.3.1+1
  json_annotation: ^3.0.0
  duration: ^2.0.8
  uuid: ^2.0.2
  flutter_typeahead: ^1.7.0
  flutter_easyrefresh: ^2.0.4
  html_unescape: ^1.0.1+3
  flutter_cupertino_settings: ^0.2.0
  url_launcher: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  build_runner: ^1.7.1
  json_serializable: ^3.2.3

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/icon_android.png"
  image_path_ios: "assets/images/icon_ios.png"
  adaptive_icon_background: "#B9D5DE"
  adaptive_icon_foreground: "assets/images/icon_android.png"
