name: timetracker
description: Papierkram.de - TimeTracker as flutter app

publish_to: 'none'

version: 1.5.5+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  http: ^0.12.2
  shared_preferences: ^2.0.4
  flutter_secure_storage: ^4.1.0
  json_annotation: ^3.0.1
  duration: ^3.0.6
  uuid: ^2.2.2
  flutter_typeahead: ^2.0.0
  flutter_easyrefresh: ^2.1.8
  html_unescape: ^1.0.2
  flutter_cupertino_settings: ^0.4.0
  url_launcher: ^5.7.10
  in_app_purchase: ^0.3.4+16
  app_review: ^2.0.1
  file_picker: ^2.1.1
  open_file: ^3.0.3
  flutter_cache_manager: ^2.0.0
  sentry_flutter: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/icon_android.png"
  image_path_ios: "assets/images/icon_ios.png"
  adaptive_icon_background: "#B9D5DE"
  adaptive_icon_foreground: "assets/images/icon_android.png"

flutter_native_splash:
  image: "assets/images/icon_splash.png"
  color: "#B9D5DE"
